/*
 * ============================================================
 *  ELEVENTY CONFIGURATION  —  eleventy.config.js
 * ============================================================
 *
 *  This is the main config file for Eleventy (11ty).
 *  Think of it as the control center for how your site gets built.
 *
 *  KEY CONCEPTS:
 *  - Eleventy reads source files from `src/` and outputs static
 *    HTML to `_site/`.  No PHP, no server-side rendering — just
 *    plain HTML files that any web server can host.
 *  - Templates use Nunjucks (.njk), a templating language similar
 *    to PHP includes but with more features (inheritance, filters,
 *    macros, etc.).
 *  - Data files in `src/_data/` are automatically available in
 *    every template.  For example, `site.json` is accessible as
 *    `{{ site.name }}` in any .njk file.
 *  - Files in `src/_includes/` are layouts and partials — they
 *    are NOT rendered as pages, only pulled in by other templates.
 *
 *  COMMANDS:
 *    npm start   →  Builds the site + starts a live-reload dev server
 *    npm run build  →  Builds the site for production into _site/
 *
 * ============================================================
 */

module.exports = function (eleventyConfig) {
	/* ----------------------------------------------------------
	 *  PASSTHROUGH COPIES
	 * ----------------------------------------------------------
	 *  Static assets that Eleventy should copy as-is into _site/
	 *  without processing.  All static assets live under src/assets/
	 *  and are served at /assets/ in the built site.
	 * ---------------------------------------------------------- */
	eleventyConfig.addPassthroughCopy("src/assets");

	// Copy favicon.ico to the site root  (src/favicon.ico → _site/favicon.ico)
	eleventyConfig.addPassthroughCopy({ "src/favicon.ico": "favicon.ico" });

	// .htaccess is now generated by src/htaccess.njk (not passthrough copy)

	/* ----------------------------------------------------------
	 *  WATCH TARGETS
	 * ----------------------------------------------------------
	 *  By default Eleventy watches .njk/.md files for changes.
	 *  We tell it to also watch CSS and JS so the dev server
	 *  reloads when you edit styles or scripts.
	 * ---------------------------------------------------------- */
	eleventyConfig.addWatchTarget("src/assets/");

	/* ----------------------------------------------------------
	 *  CACHE-BUSTING
	 * ----------------------------------------------------------
	 *  A build timestamp appended to local CSS/JS URLs as ?v=...
	 *  Forces browsers to fetch fresh assets after each build.
	 *  Available in templates as {{ cacheBust }}.
	 * ---------------------------------------------------------- */
	eleventyConfig.addGlobalData("cacheBust", Date.now());

	/* ----------------------------------------------------------
	 *  CUSTOM FILTERS
	 * ----------------------------------------------------------
	 *  Filters transform data inside templates.
	 *  Usage in Nunjucks:  {{ someValue | filterName }}
	 * ---------------------------------------------------------- */

	// {% year %} shortcode — outputs the current year (for copyright notices)
	// Usage:  2014–{% year %}
	eleventyConfig.addShortcode("year", () => `${new Date().getFullYear()}`);

	// {{ "https://example.com/page" | hostname }}  →  "example.com"
	// Extracts the hostname from a full URL (used on the projects page).
	eleventyConfig.addFilter("hostname", (url) => {
		try {
			return new URL(url).hostname;
		} catch {
			return url;
		}
	});

	// {{ page.date | isoDate }}  →  "2026-03-22"
	// Formats a JS Date object as an ISO date string (for sitemap.xml).
	eleventyConfig.addFilter("isoDate", (date) => {
		return (date instanceof Date ? date : new Date(date)).toISOString().split("T")[0];
	});

	/* ----------------------------------------------------------
	 *  DIRECTORY STRUCTURE
	 * ----------------------------------------------------------
	 *  This tells Eleventy where to find things:
	 *
	 *  input:    "src"          →  All your source files live here
	 *  output:   "_site"        →  Built site ends up here (deploy this)
	 *  includes: "_includes"    →  Layouts & partials  (relative to input)
	 *  data:     "_data"        →  Global data files   (relative to input)
	 *
	 *  The underscore prefix (_) is an Eleventy convention meaning
	 *  "this folder is for internal use, don't turn its files into pages."
	 * ---------------------------------------------------------- */
	return {
		dir: {
			input: "src",
			output: "_site",
			includes: "_includes",
			data: "_data",
		},

		// Which template languages Eleventy should process.
		// - njk  = Nunjucks templates (our primary language)
		// - md   = Markdown files (great for blog posts or content pages)
		// - html = Plain HTML files (passed through with data processing)
		templateFormats: ["njk", "md", "html"],

		// Use Nunjucks as the engine for .html files too,
		// so you can use {{ variables }} even in plain .html files.
		htmlTemplateEngine: "njk",
		markdownTemplateEngine: "njk",
	};
};
